version: '3'
services:
  haproxy:
    build: 
      context: haproxy
      dockerfile: Dockerfile.haproxy
    ports:
      - 30200:9000
      - 30100:9001
      - 80:80
    env_file:
      - .env
  minio:
    image: minio/minio
    env_file:
      - .env
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
  blog:
    build: 
      context: blog
      dockerfile: Dockerfile.server
    depends_on:
      - minio
    env_file:
      - .env
    working_dir: /app
    command: gunicorn -w 4 -b 0.0.0.0:80 server:app