version: '3'
services:
  haproxy:
    build: 
      context: haproxy
      dockerfile: Dockerfile.haproxy
    ports:
      - 30200:9000
      - 30100:9001
      - 80:80
    env_file: # quotes around variables are not trimmed
      - ./haproxy/.haproxy.env
    volumes:
      - ./haproxy:/haproxy
    depends_on:
      - blog
      - minio
      - mongodb
  blog:
    build: 
      context: blog
      dockerfile: Dockerfile.server
    depends_on:
      - minio
      - mongodb
    env_file:
      - ./blog/.server.env
    working_dir: /app
    command: gunicorn -w 4 -b 0.0.0.0:80 app:app
  minio:
    image: minio/minio
    env_file:
      - ./minio/.minio.env
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
  mongodb:
    image: mongo:latest
    volumes:
      - ./db/data:/data/db
    env_file:
      - ./mongodb/.mongo.env