version: '3'
services:
  haproxy:
    # image: blog-haproxy-1
    build: 
      context: haproxy
      dockerfile: Dockerfile.haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - 0.0.0.0:30200:9000
      - 0.0.0.0:30100:9001
      - 0.0.0.0:8080:80
      - 0.0.0.0:33333:33333
    env_file:
      - ./haproxy/.haproxy.dev.env
    depends_on:
      - server
      - minio
      - mongodb
  server:
    # image: server:latest
    build: 
      context: server
      dockerfile: Dockerfile.server
    env_file:
      - ./server/.server.dev.env
    depends_on:
      - minio
      - mongodb
    working_dir: /app
    volumes:
      - ./server:/app
    command: python3 app.py
    restart: unless-stopped
  minio:
    image: minio/minio
    env_file:
      - ./minio/.minio.dev.env
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
  mongodb:  
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./mongodb/.mongodb.env
  # nginx-rtmp:
  #   image: tiangolo/nginx-rtmp
  #   container_name: nginx_rtmp
  #   ports:
  #     - "1935:1935"  # RTMP Port
  #     - "8080:80"    # HTTP Port for HLS
  #   volumes:
  #     - ./nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf:ro  # Custom NGINX configuration
  #     - ./nginx-rtmp/hls:/tmp/hls  # Local HLS directory (will later be uploaded to Minio)
  #   depends_on:
  #     - minio
  # debug:
  #   image: debug:latest
volumes:
  mongodb_data:
    name: mongodb_data