version: '3'
services:
  haproxy:
    image: haproxy:2.3
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - 30100:9001
    env_file:
      - .env
  minio:
    image: minio/minio
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./server:/app
    working_dir: /app
    command: python3 server.py