version: '3'
services:
  haproxy:
    build: 
      context: haproxy
      dockerfile: Dockerfile.haproxy
    ports:
      - 80:80
      - 30200:9000
      - ${TAILSCALE_IP}:33333:33333
      - ${TAILSCALE_IP}:30100:9001 
    env_file: # quotes around variables are not trimmed
      - ./haproxy/.haproxy.env
    volumes:
      - ./haproxy:/haproxy
    depends_on:
      - server
      - minio
      - mongodb
  server:
    build: 
      context: server
      dockerfile: Dockerfile.server
    depends_on:
      - minio
      - mongodb
    env_file:
      - ./server/.server.env
    working_dir: /app
    command: gunicorn -w 4 -b 0.0.0.0:80 app:app
  minio:
    image: minio/minio
    env_file:
      - ./minio/.minio.env
    volumes:
      - /mnt/blog-volume/minio/data:/data
    command: server /data --console-address ":9001"
  mongodb:
    image: mongo:latest
    volumes:
      - /mnt/blog-volume/mongodb/data:/data/db
    env_file:
      - ./mongodb/.mongodb.env