FROM python:3.11-alpine

WORKDIR /app

# Install ffmpeg using apk
RUN apk update && apk add --no-cache ffmpeg

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY templates ./templates
COPY routes ./routes
COPY static ./static
COPY scripts ./scripts
COPY templates ./templates
COPY app.py ./

CMD [ "python3", "app.py" ]