FROM haproxy:2.3

RUN apt-get update && apt-get install -y gettext-base && rm -rf /var/lib/apt/lists/*

COPY haproxy.cfg.template /usr/local/etc/haproxy/haproxy.cfg.template

CMD envsubst < /usr/local/etc/haproxy/haproxy.cfg.template > /usr/local/etc/haproxy/haproxy.cfg && \
    haproxy -f /usr/local/etc/haproxy/haproxy.cfg