name: Deploy new version
on:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Sync latest changes
      env:
        DOCKER_COMPOSE_PATH: /home/luddite478/blog
      run: |
        echo 111111111111111111111111111111111111111111111
        echo $DOCKER_COMPOSE_PATH
        pwd
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} << 'EOF'
          cd $DOCKER_COMPOSE_PATH
          git pull origin master
        EOF

    - name: Stop and rerun Docker Compose
      env:
        DOCKER_COMPOSE_PATH: /home/luddite478/blog
      run: |
        echo 111111111111111111111111111111111111111111111
        echo $DOCKER_COMPOSE_PATH
        pwd
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} << 'EOF'
          cd $DOCKER_COMPOSE_PATH
          docker-compose down
          docker-compose up --build --force-recreate -d
        EOF