name: Deploy secrets

on:
  workflow_dispatch:

env:
  REPO_DIR_PATH: /home/luddite478/blog

jobs:
  redeploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [server] # Add your environments here

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Sync latest changes
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} << EOF
          cd "${{ env.REPO_DIR_PATH}}"
          git config --global --add safe.directory ${{ env.REPO_DIR_PATH}}
          git pull origin master
        EOF

    - name: Substitute Environment Variables
      uses: ./.github/actions/env-vars-substitute
      with:
        example_env_file: server/.server.example.env
        output_env_file: server/.server.env

    - name: Upload .server.env to server
      run: |
        scp -o StrictHostKeyChecking=no server/.server.env ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }}:${{ env.REPO_DIR_PATH }}/server/.server.env

    - name: Stop and rerun Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} << EOF
          cd "${{ env.REPO_DIR_PATH}}"
          docker-compose down
          docker-compose up --build -d
        EOF