name: Deploy secrets

on:
  workflow_dispatch:

env:
  REPO_DIR_PATH: /home/luddite478/blog

jobs:
  initial-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Sync latest changes
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} << EOF
          cd "${{ env.REPO_DIR_PATH}}"
          git config --global --add safe.directory ${{ env.REPO_DIR_PATH}}
          git pull origin master
        EOF

  redeploy:
    needs: initial-setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [server, haproxy]
    environment: ${{ matrix.environment }}
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Read and Substitute Environment Variables
      run: |
        # Read the example env file and substitute values
        echo '${{ toJSON(secrets) }}' > secrets.json
        echo '${{ toJSON(vars) }}' > vars.json

        echo "Reading and substituting environment variables..."
        cat ${{ matrix.environment }}/.${{ matrix.environment }}.example.env

        while IFS='=' read -r key value; do
          # Remove leading and trailing spaces
          key=$(echo $key | xargs)
          
          # Check if the key is not empty and doesn't start with a comment
          if [[ ! -z "$key" && ! $key =~ ^# ]]; then
            # Get the corresponding secret value from the JSON file
            secret_value=$(jq -r --arg key "$key" '.[$key]' secrets.json)
            
            # Debug output
            echo "Processing key: $key"
            echo "Original value: $value"
            echo "Secret value: $secret_value"
            
            # If the secret exists, substitute it in the .env file
            if [[ ! -z "$secret_value" && "$secret_value" != "null" ]]; then
              echo "$key=$secret_value" >> ${{ matrix.environment }}/.${{ matrix.environment }}.env
            else
              echo "$key=$value" >> ${{ matrix.environment }}/.${{ matrix.environment }}.env
            fi
          fi
        done < ${{ matrix.environment }}/.${{ matrix.environment }}.example.env

        echo "Resulting .${{ matrix.environment }}.env file:"
        cat ${{ matrix.environment }}/.${{ matrix.environment }}.env

    - name: Upload .env to server
      run: |
        scp -o StrictHostKeyChecking=no ${{ matrix.environment }}/.${{ matrix.environment }}.env ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }}:${{ env.REPO_DIR_PATH }}/${{ matrix.environment }}/.${{ matrix.environment }}.env

    # - name: Stop and rerun Docker Compose
    #   run: |
    #     ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} << EOF
    #       cd "${{ env.REPO_DIR_PATH}}"
    #       docker-compose down
    #       docker-compose up --build -d
    #     EOF